spring.application.name=payment-api

spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

aes.secret.key=${AES_SECRET_KEY}
api.secret.key=${API_SECRET_KEY}


spring.datasource.initialization-mode=always
spring.datasource.hikari.maximum-pool-size=10

server.port=8080




